Fix filter editor's dark background on Mac OS 12
Sequel-Ace/Sequel-Ace pull request #1890
Opened 2023-10-17 15:35 UTC by elosha

## Changes:
- Changed background of DBView filter editor to non-drawing

## Closes following issues:
- Closes: #1841

## Tested:
- Processors:
  - [ ] Intel
  - [x] Apple Silicon
- macOS Versions:
  - [ ] 10.13.x (High Sierra)
  - [ ] 10.14.x (Mojave)
  - [ ] 10.15.x (Catalina)
  - [ ] 11.x (Big Sur)
  - [x] 12.x (Monterey)
  - [ ] 13.x (Ventura)
  - [ ] 14.x (Sonoma)
- Localizations:
  - [x] English
  - [ ] Spanish
  - [x] German
- Xcode Version: 14
  
## Screenshots:
Before:
<img width="294" alt="Bildschirmfoto 2023-10-16 um 19 07 38" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/30213185/8c26ed4b-5eca-448d-8399-a45c5a340276">
After:
<img width="305" alt="Bildschirmfoto 2023-10-17 um 17 28 31" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/30213185/1748cbcf-c956-42c9-bd1d-341887309567">

## Additional notes:

2023-10-18 01:01 UTC, Jason-Morcos requested changes
Hi @elosha - I appreciate the fix PR!

I think, unfortunately, this looks less optimal on the latest macOS 14. I've included some screenshots here. I think this PR removes the contrast between the filter bar and table content and makes the view less visually distinct - and also introduces a contrast with the right side of the bar. Perhaps a more nuanced (os-specific, in the code switch) approach might be needed here


**Current Main:**
<img width="1797" alt="Screenshot 2023-10-17 at 17 57 30" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/10710367/87220238-6f59-461a-b4c3-f63f2e25187d">
<img width="1796" alt="Screenshot 2023-10-17 at 17 57 16" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/10710367/8c6046a4-66f7-4494-a9f7-adef42a1dd2b">



**This PR:**
<img width="1792" alt="Screenshot 2023-10-17 at 17 56 15" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/10710367/3600eab1-cea1-454a-8629-6d2e7794c305">
<img width="1797" alt="Screenshot 2023-10-17 at 17 56 33" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/10710367/0ab0fa92-3c2c-4862-9554-11ca8b84fbe3">

2023-10-18 14:05 UTC, elosha commented
@Jason-Morcos Ok, I see … we need to find out why it appears so differently. Of course the current look you see on OS 14 is perfect! However it's just mixed together …
– by overlaying(!) the actual controls with the panel
– using a text color as background color
– with alpha transparency
… therefore the actual outcome is very fragile and dependent on OS, appearance and accessibility settings (remember "reduce transparency"!

I don't think we need a switch, just a proper color definition and drawing order ;)

2023-10-18 14:29 UTC, Jason-Morcos commented
I don't disagree at all - honestly, @elosha, I spent a couple hours of my time on it a few weeks ago and couldn't get things to play nice so I punted on working on it further. I'd gladly review PRs like this one that aim to fix it, but I don't have additional time to spend on this at this time :/

2023-11-02 18:22 UTC, nexbridge commented
@elosha Thanks for trying to fix this - I'm having a similar problem on Ventura.  Is there a way of setting the background colour to match that of the right-hand panel (where the Apply Filters button is), as that was how it looked previously?

2023-11-06 04:01 UTC, Jason-Morcos commented
Closing due to inactivity

2023-11-06 04:01 UTC, closed without merging