Added info on how to move "quick connect" connections
Sequel-Ace/Sequel-Ace pull request #398
Opened 2020-10-13 17:25 UTC by mcinp

What does this implement/fix? Explain your changes.
---------------------------------------------------
I stumbled upon the problem of moving quick connect connections from Sequel Pro to Sequel Ace. This notion in the readme addresses this issue.

Does this close any currently open issues?
------------------------------------------
No

Any relevant logs, error output, etc?
-------------------------------------
No

Any other comments?
-------------------
No

Where has this been tested?
---------------------------
N/A

**Devices/Simulators:** …

**macOS Version:** …

**Sequel-Ace Version:** …

2020-10-13 18:15 UTC, Kaspik requested changes

2020-10-13 18:15 UTC, Kaspik commented on readme.md
> +to ~/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Application Support/Sequel Ace/Data
```suggestion
`~/Library/Application Support/Sequel Pro/Data/Favorites.plist` to `~/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Application Support/Sequel Ace/Data`
```

2020-10-13 18:15 UTC, Kaspik commented on readme.md
> +```cp ~/Library/Application\ Support/Sequel\ Pro/Data/Favorites.plist ~/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Application\ Support/Sequel\ Ace/Data```
```suggestion
```
```
cp ~/Library/Application\ Support/Sequel\ Pro/Data/Favorites.plist ~/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Application\ Support/Sequel\ Ace/Data
```

2020-10-29 00:10 UTC, Jason-Morcos commented
No discussion in 15 days - closing this PR. If @Kaspik's comments are addressed, then feel free to re-open PR :)

2020-10-29 00:10 UTC, closed without merging